id: IB4566E04
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:17:46+00:00'
last_modified: '2022-06-08T12:30:01.798848+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5120
  title: རྒྱུན་འཕྱེར་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས་དད་ལྡན་ཡིད་ཀྱི་དགའ་སྟོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C522:
      image_group_id: I3CN5122
      title: ''
      total_pages: 156
      order: 1
      base_file: C522.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
