id: IB4566E04
legacy_id: P006922
ocr_import_info:
  bdrc_scan_id: W3CN5120
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T20:16:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:52:04.639341+00:00'
last_modified: 2022-09-03 22:52:11.494512
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5120
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5120
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུན་འཕྱེར་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས་དད་ལྡན་ཡིད་ཀྱི་དགའ་སྟོན།
statistics:
  ocr_word_mean_confidence_index: 0.9261513269686406
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3CN5122:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5122
      total_pages: 156
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5122.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9261513269686406
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
